#应用服务web端口
server:
  port: 80
person:
  name: zhangsan
  age: 18
  addr: guangxi
  adr: hhh
Student: {name: lisi,age: 22,gender: girl}
#配置数组、集合
cities:
  city:
    - beijing
    - hainan
    - yunnan
city2: [beijing,hainan,yunan]
girls:
  girl:
    - name: 凤姐
      age: 22
      adr: 四川
    - name: 美女
      age: 33
      gender: girl
      adr: 南宁
帅哥:
  - name: 李才汶
    age: 21
    addr: 海南
    年级: 大三
明星: [{姓名: 刘德华,年龄: 22},{姓名: 张学友,年龄: 32},{姓名: 黎明,年龄: 44},{姓名: 郭富城}]

Map:
  key1: value1
  key2: value2
  key3: value3
  key4: value4
账号密码:
  张三: 123
  李四: 258;
  刘德华: 333;
  火影忍者: 2333;

#四大名著
books:
   xiyouji:
      - renwu:
          - 姓名: 猪八戒
            性别: 男
          - 姓名: 孙悟空
            性别: 男
          - 姓名: 唐僧
            性别: 男
          - 姓名: 沙悟净
            性别: 男
      - bingqi:
          - 名字: 定海神针
            重量: 100000t
          - 名字: 猪耙
            重量: 1000t
          - 名字: 铁铲
            重量: 1005t
      - 成就:
          - 终级: 斗战胜佛
          - 终级: 净坛使者
          - 终级: 金蝉子
      - xianji:
          - 初级: 石猴
          - 初级: 猪刚鬣
   红楼梦:
      - 人物:
      - 兵器:
      - 成就:
      - 人级:
   三国演义:
      - 人物:
      - 兵器:
      - 成就:
      - 地级:
   水浒传:
      - 人物:
      - 兵器:
      - 成就:
      - 天级:
